language: go

go:
  - '1.10'

services:
  - docker

before_script:
  - curl -L https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 > $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - dep ensure --vendor-only
  - go get ./vendor/gopkg.in/bblfsh/sdk.v2/cmd/...
  - go install ./vendor/gopkg.in/bblfsh/sdk.v2/cmd/...
  - docker pull bblfsh/bblfshd

script:
  - bblfsh-sdk update --dry-run
  - bblfsh-sdk build ci-build
  - bblfsh-sdk test ci-build

after_success:
  - bblfsh-sdk push ci-build
